### ISSUE TITLE
Bad results on animating wild videos

### ISSUE THREAD

**Issue by FeiiYin** [RenYurui/PIRender#13]
Thanks for your impressive work!
I used DeepFaceRecon_pytorch to achieve the 3dmm params. But got bad results.
And for same test demo video in the VoxCeleb, the params are different.
Can you help me figure it out which procedure in the pre-processing got wrong?
Thanks in advance!
![image](https://user-images.githubusercontent.com/28101823/139198418-c23458a7-aee0-49ba-9e68-66e8aab7d81c.png)

**Comment by YuDeng** [comment]
> Solved, I change the transform_params to default and it worked for me.

Hi, I wonder how you set the transform_params to default? I've met a similar issue.

**Comment by FeiiYin** [comment]
@YuDeng 

Hi, YuDeng. The problem is due to the incorrect input image resolution when feeding into 3DMM.
It seems the 3DMM model cannot predict accurate parameters for high-resolution images.
If you resize the input image to 256, I guess it will be ok.

By the way, I am a big fan of your work, DeepFaceReconstruction, GRAM, GRAM-HD, all leave me a great impression.
Is it possible to add wechat of you? I am currently a master student at Tsinghua university.
If it is possible, I may send my wechat number to your email.

**Comment by YuDeng** [comment]
> @YuDeng
> 
> Hi, YuDeng. The problem is due to the incorrect input image resolution when feeding into 3DMM. It seems the 3DMM model cannot predict accurate parameters for high-resolution images. If you resize the input image to 256, I guess it will be ok.
> 
> By the way, I am a big fan of your work, DeepFaceReconstruction, GRAM, GRAM-HD, all leave me a great impression. Is it possible to add wechat of you? I am currently a master student at Tsinghua university. If it is possible, I may send my wechat number to your email.

I fix the issue following your suggestion.  Thanks!
Of course, let's talk via wechat :D
