### ISSUE TITLE
Question about method comparison

### ISSUE THREAD

**Issue by xk-huang** [RenYurui/PIRender#6]
Thanks for sharing your exciting work about portrait editing!
I have a question about the comparison between PIRender and StyleRig. As there is no open-source implementation of StyleRig, I'm wondering did you implement it by yourself or asked the authors to conduct the experiment? I'm wondering whether the implementation gaps affect the final outcomes or not.
Thanks again for sharing your work!

**Comment by RenYurui** [comment]
Hi, 
We re-implement StyleRig on our own. 
We use the implementation details provided by the paper. Some details are different. For example, StyleRig uses a different expression model which is not publicly available. 
We find the trained model tends to generate images with a conservative strategy: motions away from the distribution center are weakened or ignored. We tried many times but fail to improve the results. 
However, I think this may not affect the final conclusion (the advantages and disadvantages of the methods). 
Yurui

**Comment by xk-huang** [comment]
Thanks for your kind reply!

**Comment by lastapple** [comment]
对比实验我也很困扰，不仅stylerig不开源，PIE也没开源，PhotoApp更无，不是不能自己复现而是怕不太公平或者效果不一样。
